### ISSUE TITLE
Create a new Tanach parser

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-text2json#49]
(Lets continue the conversation here. Create an issue for each task you are working on. If you need my attention, add @omishali once.)

Very good work!

Some comments:
- Use the method addWithin in JbsParser.
- Add an ending ":" to pasuk text nikud.
- No need to copy SEFARIM_TANACH_URI_EN? it is public.
- Add a few public static methods to JbsUtils to get the different URIs. Then remove the private ones that you created and use them instead. Use these static methods whenever needed from the mefarshim parsers as well.
  - String getPasukUri(int sefer, int perek, int pasuk)
  - String getTanachPerekUri(int sefer, int perek)
  - String getTorahParashaUri(int parasha)
- Add more test: the number of parashot is 54, the number of perakim is 929.
- tanach-packages: the position of a perek should continue and not restarted.

**Comment by omishali** [comment]
I did some refactoring so pull before.

**Comment by orelkan** [comment]
OK, I have a few questions:

>Add an ending ":" to pasuk text nikud

I there already is one in the raw text. Although maybe it's a different character that looks the same. Could you look at the tanach.json again and just tell me if it's the wrong character, and I should just change the last character to the ":" character?

>tanach-packages: the position of a perek should continue and not restarted

Every perek has a different jbo:book property, so it made sense that the positions reset. In every book the pereks truly reset. So if you want me to change that yes I will change it I just want it to be clear.

**Comment by omishali** [comment]
1. It exists in the raw text but somehow is removed in the text with nikud.
1. Please make the change.

**Comment by orelkan** [comment]
I made the changes, also pushed them to jbs-data. Please take a look

**Comment by omishali** [comment]
It looks good, besides the ":" issue which I don't understand.
The raw input text has ":" at the end of each pasuk line, then why this character is not represented in the output file? Currently you add it explicitly to the text without nikud but it should exist without no firther addition.

**Comment by orelkan** [comment]
I didn't understand why it didn't show at your files, because in my file editor the ":" character did exist.
This character in the nikud is different than the normal ":" character (I checked using character to number converters), so I assumed some editors didn't show the character properly or something like that. So I decided to manually replace the character with the normal ":" character.
As I said, in my file editor (gedit on Ubuntu) I did see the whole nikud line, including the hebrew ":" character on the json file

**Comment by omishali** [comment]
I also see it in my editor but I don't see it in GitHub in the json file...
(now I see it for the text with nikud but not for the text without the
nikud).

‫בתאריך יום א׳, 29 ביולי 2018 ב-16:06 מאת ‪orelkan‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by omishali** [comment]
It is not removed as part of the removeNikud method. See the test I added
to JbsUtilsTest. Try to find the lost ":" character.

‫בתאריך יום א׳, 29 ביולי 2018 ב-16:24 מאת ‪orelkan‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by orelkan** [comment]
That's because in your test you have the normal : character:
:
However in the raw text there is this character:
׃
They are not the same. The other one gets removed.
