### ISSUE TITLE
Create parser for Abarbanel and improve the design

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-text2json#51]
Created a new raw file for "abarbanel". Besides implementing the parser I want you to support a different design where we do not create a new class for each new mefaresh (considering the minimal data in each new class, a different solution is needed).

Please do the following:
- Create a new folder jbs-data/raw/tanachmefarshim
- Place ramban.txt and abarbanel.txt within that folder.
- Remove the folders ramban and abarbanel.
- Keep only the MefareshParser class (no need for subclasses).
- Update the configParsers file: add MefareshParser and update the input/output folder.

The Text2Json class, if it finds N files within an input directory it executes the parser N times on each of the files.

This means that we should also have one test for all the mefarshim.

**Comment by orelkan** [comment]
OK, but how will the parser know which mefaresh it currently parses? It needs to know the name and Hebrew name. My only other idea is to get these 2 strings in the Constructor of the MefareshParser class. Is it possible to set this in the config file or on Text2Json main? Is this the way you meant?

Thanks

**Comment by omishali** [comment]
I suggest that the first line in the input text file will tell that.
Currently the first line contains text like "רמב"ן" or "אברבנאל". You can
add the word פירוש before that so you will be identify the first line act
upon.

‫בתאריך יום ב׳, 30 ביולי 2018 ב-23:04 מאת ‪orelkan‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by orelkan** [comment]
My commit finishes this assignment, I also added a test class. Please take a look.
The json files were also uploaded to jbs-data

**Comment by omishali** [comment]
Looks good.
- in MefareshParserTest, create a separate test method for each perush.
- In MefareshParser, add a comment next to "special" matchers that are specific to a few of the perushim (e.g., hakdamot in Ramban). In the comment mention the name of the perush it applies to. This will help in understanding which the generic matchers and which are "perush-specific".
